# **PANDAS 101**
> ## *Author* : [Rathachai CHAWUTHAI](https://rathachai.creatier.pro/) , Ph.D
> ### *Affiliation* : Computer Engineering, King Mongkut's Institute of Technology Ladkrabang (KMITL)
> #### *Updated Date* : 2025-10-05
---

> <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.



---

## Prerequisite Knowledge
> Python, List, Dictionary, Tuple, Function, Lambda, Numpy, and CSV


## Agenda

**Review**
*   Basic Python
*   About Dataset
*   Basic Numpy

**Pandas**
*   Series & Dataframe
*   Read CSV into a Pandas Dataframe
*   Column Selection
*   Row Selection
*   Row and Column Selection (1)
*   Cell Modification
*   Set Index
*   Row and Column Selection (2)
*   Reset Index
*   Range Selection
*   Conditinal Selection
*   Column Operation
*   New Column
*   Drop Row
*   Drop Column
*   Sorting (1)
*   Sorting (2)
*   Grouping (1)
*   Grouping (2)
*   Iteration
*   Apply Function
*   Save Dataframe into a CSV file


## Instruction

1.   Menu "File"
2.   "Save a Copy in Drive"



## Basic Python

In [843]:
print('hello world')

hello world


In [844]:
print("hello world")

hello world


In [845]:
1+1

2

In [846]:
print('1 + 1 = ', 1+1)

1 + 1 =  2


In [847]:
arr = [0, 10, 20, 30]

In [848]:
arr[1]

10

In [849]:
arr[0] + arr[1]

10

In [850]:
len(arr)

4

In [851]:
for i in arr:
  print(i)

0
10
20
30


**Quiz !!**

> เขียน code เพื่อบวกเลขใน arr ทั้งหมด และแสดงคำตอบ

In [852]:
# Answer
results = 0
for i in arr:
  results += i

print(results)

60


## About a Dataset

Click [https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv](https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv)

## Import Libraries

In [853]:
import numpy as np
import pandas as pd

## Basic Numpy

In [854]:
[1,2,3] + [10,10,10]

[1, 2, 3, 10, 10, 10]

In [855]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [856]:
np.array([1,2,3]) + np.array([10,10,10])

array([11, 12, 13])

In [857]:
np.array([1,2,3]) * 3

array([3, 6, 9])

In [858]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [859]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [860]:
np.arange(5,10,2)

array([5, 7, 9])

In [861]:
np.random.rand(5)

array([0.50374376, 0.94392306, 0.04215675, 0.26594886, 0.95528594])

In [862]:
np.random.randint(10,20,5)

array([17, 13, 16, 18, 18])

In [863]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [864]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**Quiz !!**

> แสดงคำตอบเป็น array ของเลข [3, 3, 3, 3, ..] จำนวน 20 ตัว

In [865]:
# Answer
np.ones(20)*3


array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3.])

In [866]:
x = np.arange(0,5)

In [867]:
x

array([0, 1, 2, 3, 4])

In [868]:
x.sum()

np.int64(10)

In [869]:
np.sum(x)

np.int64(10)

In [870]:
x.mean()

np.float64(2.0)

In [871]:
x.min()

np.int64(0)

In [872]:
x.max()

np.int64(4)

In [873]:
x.std()

np.float64(1.4142135623730951)

In [874]:
x

array([0, 1, 2, 3, 4])

In [875]:
x[2]

np.int64(2)

In [876]:
x[0:3]

array([0, 1, 2])

In [877]:
x[:3]

array([0, 1, 2])

In [878]:
x[3:]

array([3, 4])

In [879]:
x[-1]

np.int64(4)

In [880]:
x[-2]

np.int64(3)

**Quiz !!**

> จงใช้ numpy เพื่อบวกเลขตั้งแต่ 1 ถึง 20

In [881]:
# Answer
nup_1 = np.arange(1, 21)
result_nup_1 = nup_1.sum()
result_nup_1

np.int64(210)

## Pandas Series & Pandas Dataframe

In [882]:
s1 = pd.Series([0, 10, 20])

In [883]:
s1

0     0
1    10
2    20
dtype: int64

In [884]:
s1.mean()

np.float64(10.0)

In [885]:
s1.max()

20

In [886]:
s2 = pd.Series(["A", "B", "C"])

In [887]:
s2

0    A
1    B
2    C
dtype: object

In [888]:
df = pd.DataFrame({"name":s2, "working_years":s1})

In [889]:
df

name  working_years
0    A              0
1    B             10
2    C             20

In [890]:
type(df)

pandas.core.frame.DataFrame

In [891]:
type(s1)

pandas.core.series.Series

In [892]:
df["name"]

0    A
1    B
2    C
Name: name, dtype: object

In [893]:
df[["name"]]

name
0    A
1    B
2    C

In [894]:
type(df["name"])

pandas.core.series.Series

In [895]:
type(df[["name"]])

pandas.core.frame.DataFrame

**Quiz !!**

> จงสร้าง Dataframe แบบนี้จาก Series

| Code  | From | To  |
|-------|------|-----|
| TG608 | HKT  | HKG |
| TG677 | NRT  | BKK |
| TG678 | BKK  | CAN |

In [896]:
s1 = pd.Series(["TG608", "TG677", "TG678"])
s2 = pd.Series(["HKT", "NRT", "BKK"])
s3 = pd.Series(["HKG", "BKK", "CAN"])

df = pd.DataFrame({"Code":s1, "From":s2, "To":s3})
df

Code From   To
0  TG608  HKT  HKG
1  TG677  NRT  BKK
2  TG678  BKK  CAN

## Read CSV into a Pandas Dataframe

In [897]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [898]:
df = pd.read_csv(CSV_PATH)

In [899]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [900]:
df.head()

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [901]:
df.tail()

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

**Quiz !!**

> แสดง 4 แถวแรก

In [902]:
df.head(4)

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

## Column Selection

In [903]:
df["name"]

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [904]:
df[["name"]]

name
0      Anda
1    Bordin
2  Chantana
3   Donlaya
4   Ekkasit
5    Fundee
6   Gitiwit
7     Harit

In [905]:
df[["name", "gender", "age"]]

name  gender  age
0      Anda  female   39
1    Bordin    male   25
2  Chantana  female   29
3   Donlaya  female   39
4   Ekkasit    male   37
5    Fundee  female   35
6   Gitiwit    male   26
7     Harit    male   32

**Quiz !!**

> แสดงคอลัมน์ age แล้วตามด้วย name

In [906]:
df[["name", "age"]]

name  age
0      Anda   39
1    Bordin   25
2  Chantana   29
3   Donlaya   39
4   Ekkasit   37
5    Fundee   35
6   Gitiwit   26
7     Harit   32

## Row Selection

In [907]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary             48700.0
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [908]:
df.loc[[1]]

eid    name gender department  age   salary  working_years birth_place
1  E012  Bordin   male  developer   25  48700.0              2      Phuket

In [909]:
df.loc[[1,2,3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

**Quiz !!**

> จงแสดงแถวที่ 3 แล้วตามด้วย 1

In [910]:
df.loc[[3, 1]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
1  E012   Bordin    male  developer   25  48700.0              2      Phuket

## Row and Column Selection (1)

In [911]:
df.loc[1,["name","age"]]

name    Bordin
age         25
Name: 1, dtype: object

In [912]:
df.loc[[1], ["name","age"]]

name  age
1  Bordin   25

In [913]:
df.loc[[1,2,3], ["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [914]:
df[["name","age"]].loc[[1,2,3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [915]:
df.loc[[1,2,3]][["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

**Quiz !!**

> จงแสดงคอลัมน์ age กับ name เฉพาะแถวที่ 3 กับ 1

In [916]:
df.loc[[3, 1]][["age","name"]]

age     name
3   39  Donlaya
1   25   Bordin

## Value Modification

In [917]:
df[["name","working_years"]]

name  working_years
0      Anda              4
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [918]:
df.loc[0,"working_years"] = 77

In [919]:
df[["name","working_years"]]

name  working_years
0      Anda             77
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [920]:
df.loc[[1,2],"working_years"] = 9999

In [921]:
df[["name","working_years"]]

name  working_years
0      Anda             77
1    Bordin           9999
2  Chantana           9999
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [922]:
df.loc[[1,2],["name","working_years"]] = "MODIFIED"

/tmp/ipython-input-2587201694.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'MODIFIED' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[[1,2],["name","working_years"]] = "MODIFIED"


In [923]:
df[["name","working_years"]]

name working_years
0      Anda            77
1  MODIFIED      MODIFIED
2  MODIFIED      MODIFIED
3   Donlaya             8
4   Ekkasit             7
5    Fundee             3
6   Gitiwit             2
7     Harit             5

In [924]:
df

eid      name  gender department  age   salary working_years birth_place
0  E011      Anda  female  developer   39  64200.0            77     Bangkok
1  E012  MODIFIED    male  developer   25  48700.0      MODIFIED      Phuket
2  E013  MODIFIED  female  developer   29  45500.0      MODIFIED    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0             8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0             7  Suphanburi
5  E016    Fundee  female    support   35  56600.0             3      Phuket
6  E017   Gitiwit    male    support   26  42400.0             2  Suphanburi
7  E018     Harit    male     devops   32  67700.0             5     Bangkok

**Quiz !!**

> จงแก้ working_years ของคนสุดท้ายให้เป็น 55

In [925]:
df["working_years"].loc[7] = 55
df

/tmp/ipython-input-497314963.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["working_years"].loc[7] = 55
/tmp/ipython-input-497314963.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

S

eid      name  gender department  age   salary working_years birth_place
0  E011      Anda  female  developer   39  64200.0            77     Bangkok
1  E012  MODIFIED    male  developer   25  48700.0      MODIFIED      Phuket
2  E013  MODIFIED  female  developer   29  45500.0      MODIFIED    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0             8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0             7  Suphanburi
5  E016    Fundee  female    support   35  56600.0             3      Phuket
6  E017   Gitiwit    male    support   26  42400.0             2  Suphanburi
7  E018     Harit    male     devops   32  67700.0            55     Bangkok

## Reload the Dataframe

In [926]:
df = pd.read_csv(CSV_PATH)

In [927]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Set Index

In [928]:
df.set_index("eid")

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [929]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [930]:
df.set_index("eid", inplace=True)

In [931]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

## Row and Column Selection (2)

In [932]:
df.loc[["E011","E012"], ["name", "salary"]]

name   salary
eid                  
E011    Anda  64200.0
E012  Bordin  48700.0

In [933]:
df.iloc[0]

name                  Anda
gender              female
department       developer
age                     39
salary             64200.0
working_years            4
birth_place        Bangkok
Name: E011, dtype: object

In [934]:
df.iloc[[0]]

name  gender department  age   salary  working_years birth_place
eid                                                                   
E011  Anda  female  developer   39  64200.0              4     Bangkok

In [935]:
df.iloc[[0,1]]

name  gender department  age   salary  working_years birth_place
eid                                                                     
E011    Anda  female  developer   39  64200.0              4     Bangkok
E012  Bordin    male  developer   25  48700.0              2      Phuket

In [936]:
df.iloc[[0,1]][["name","gender"]]

name  gender
eid                 
E011    Anda  female
E012  Bordin    male

**Quiz !!**

> จงแสดง name และ age ของ E015, E016

In [937]:
df[["name", "age"]].loc[["E015", "E016"]]

name  age
eid               
E015  Ekkasit   37
E016   Fundee   35

## Reset Index

In [938]:
df.reset_index(inplace=True)

In [939]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Reload the Dataframe



In [940]:
df = pd.read_csv(CSV_PATH)

In [941]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Range Selection

In [942]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [943]:
df.loc[:4]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [944]:
df.loc[4:]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [945]:
df.loc[1:3,["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [946]:
df.iloc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

In [947]:
df.iloc[1:4][["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

## Conditional Selection

In [948]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [949]:
df[["working_years"]]

working_years
0              4
1              2
2              3
3              8
4              7
5              3
6              2
7              5

In [950]:
df["working_years"]>3

0     True
1    False
2    False
3     True
4     True
5    False
6    False
7     True
Name: working_years, dtype: bool

In [951]:
df[df["working_years"]>3]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [952]:
df[df["working_years"]>3][["name","working_years", "salary"]]

name  working_years   salary
0     Anda              4  64200.0
3  Donlaya              8  72600.0
4  Ekkasit              7  80500.0
7    Harit              5  67700.0

In [953]:
df[ (df["working_years"]>3) & (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [954]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

**Quiz !!**

> จงหาคนที่เงินเดือนระหว่าง 30000 กับ 70000

In [955]:
df[(df["salary"]>=30000) & (df["salary"]<=70000)]["name"]

0        Anda
1      Bordin
2    Chantana
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [956]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].iloc[[3]]

eid   name gender department  age   salary  working_years birth_place
7  E018  Harit   male     devops   32  67700.0              5     Bangkok

In [957]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].loc[[3]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

## Column Operation

In [958]:
df["salary"]

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [959]:
df["salary"]*12

0    770400.0
1    584400.0
2    546000.0
3    871200.0
4    966000.0
5    679200.0
6    508800.0
7    812400.0
Name: salary, dtype: float64

In [960]:
df["salary"]*df["working_years"]

0    256800.0
1     97400.0
2    136500.0
3    580800.0
4    563500.0
5    169800.0
6     84800.0
7    338500.0
dtype: float64

**Quiz !!**

> จงคำนวณภาษีรายปีของแต่ละคน ถ้าอัตราภาษีอยู่ที่ 10%

In [961]:
df["salary"]*0.1

0    6420.0
1    4870.0
2    4550.0
3    7260.0
4    8050.0
5    5660.0
6    4240.0
7    6770.0
Name: salary, dtype: float64

## New Column

In [962]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [963]:
df["country"] = "Thailand"

In [964]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country  
0  Thailand  
1  Thailand  
2  Thailand  
3  Thailand  
4  Thailand  
5  Thailand  
6  Thailand  
7  Thailand

In [965]:
df["salary"]*df["working_years"]

0    256800.0
1     97400.0
2    136500.0
3    580800.0
4    563500.0
5    169800.0
6     84800.0
7    338500.0
dtype: float64

In [966]:
df["bonus"] = df["salary"]*df["working_years"]

In [967]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

**Quiz !!**

> สร้างคอลัมน์ year_tax โดยคำนวณภาษีจากรายได้รายปีที่ 10%

In [968]:
df["year_tax"] = df["salary"]*0.1
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0    6420.0  
1  Thailand   97400.0    4870.0  
2  Thailand  136500.0    4550.0  
3  Thailand  580800.0    7260.0  
4  Thailand  563500.0    8050.0  
5  Thailand  169800.0    5660.0  
6  Thailand   84800.0    4240.0  
7  Thailand  338500.0    6770.0

## Drop Row

In [969]:
df.drop(7)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  year_tax  
0  Thailand  256800.0    6420.0  
1  Thailand   97400.0    4870.0  
2  Thailand  136500.0    4550.0  
3  Thailand  580800.0    7260.0  
4  Thailand  563500.0    8050.0  
5  Thailand  169800.0    5660.0  
6  Thailand   84800.0    4240.0

In [970]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  year_tax  
0  Thailand  256800.0    6420.0  
1  Thailand   97400.0    4870.0  
2  Thailand  136500.0    4550.0  
3  Thailand  580800.0    7260.0  
4  Thailand  563500.0    8050.0  
5  Thailand  169800.0    5660.0  
6  Thailand   84800.0    4240.0  
7  Thailand  338500.0    6770.0

In [971]:
df.drop(7, inplace=True)

In [972]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  year_tax  
0  Thailand  256800.0    6420.0  
1  Thailand   97400.0    4870.0  
2  Thailand  136500.0    4550.0  
3  Thailand  580800.0    7260.0  
4  Thailand  563500.0    8050.0  
5  Thailand  169800.0    5660.0  
6  Thailand   84800.0    4240.0

In [973]:
df.drop([0,1,2])

eid     name  gender department  age   salary  working_years birth_place  \
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  year_tax  
3  Thailand  580800.0    7260.0  
4  Thailand  563500.0    8050.0  
5  Thailand  169800.0    5660.0  
6  Thailand   84800.0    4240.0

**Quiz !!**

> จงลบแถวที่ 3

In [974]:
df.drop(2)

eid     name  gender department  age   salary  working_years birth_place  \
0  E011     Anda  female  developer   39  64200.0              4     Bangkok   
1  E012   Bordin    male  developer   25  48700.0              2      Phuket   
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  year_tax  
0  Thailand  256800.0    6420.0  
1  Thailand   97400.0    4870.0  
3  Thailand  580800.0    7260.0  
4  Thailand  563500.0    8050.0  
5  Thailand  169800.0    5660.0  
6  Thailand   84800.0    4240.0

## Drop Column

In [975]:
df.drop("country", axis=1)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

      bonus  year_tax  
0  256800.0    6420.0  
1   97400.0    4870.0  
2  136500.0    4550.0  
3  580800.0    7260.0  
4  563500.0    8050.0  
5  169800.0    5660.0  
6   84800.0    4240.0

In [976]:
df.drop(["country","bonus"], axis=1)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

   year_tax  
0    6420.0  
1    4870.0  
2    4550.0  
3    7260.0  
4    8050.0  
5    5660.0  
6    4240.0

In [977]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  year_tax  
0  Thailand  256800.0    6420.0  
1  Thailand   97400.0    4870.0  
2  Thailand  136500.0    4550.0  
3  Thailand  580800.0    7260.0  
4  Thailand  563500.0    8050.0  
5  Thailand  169800.0    5660.0  
6  Thailand   84800.0    4240.0

In [978]:
df.drop(["country","bonus"], axis=1, inplace=True)

In [979]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

   year_tax  
0    6420.0  
1    4870.0  
2    4550.0  
3    7260.0  
4    8050.0  
5    5660.0  
6    4240.0

**Quiz !!**

> จงลบคอลัมน์ age กับ name

In [980]:
df.drop(["age","name"], axis=1)

eid  gender department   salary  working_years birth_place  year_tax
0  E011  female  developer  64200.0              4     Bangkok    6420.0
1  E012    male  developer  48700.0              2      Phuket    4870.0
2  E013  female  developer  45500.0              3    Chonburi    4550.0
3  E014  female  marketing  72600.0              8    Chonburi    7260.0
4  E015    male  marketing  80500.0              7  Suphanburi    8050.0
5  E016  female    support  56600.0              3      Phuket    5660.0
6  E017    male    support  42400.0              2  Suphanburi    4240.0

## Reload the Dataframe

In [981]:
df = pd.read_csv(CSV_PATH)

In [982]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Sorting (1)

In [983]:
df.sort_values("salary")

eid      name  gender department  age   salary  working_years birth_place
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
5  E016    Fundee  female    support   35  56600.0              3      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [984]:
df.sort_values(["department","salary"])

eid      name  gender department  age   salary  working_years birth_place
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket

In [985]:
df.sort_values("salary", ascending=False)

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [986]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

**Quiz !!**

> จงเรียงลำดับ age จากน้อยไปมาก และ salary จากมากไปน้อย

In [987]:
df.sort_values(["age", "salary"], ascending=[True, False], inplace=True)
df

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
0  E011      Anda  female  developer   39  64200.0              4     Bangkok

## Sorting (2)

In [988]:
df.sort_values("salary", ascending=False, inplace=True)

In [989]:
df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [990]:
df.loc[0:2]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi

In [991]:
df.iloc[0:2]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

## Grouping (1)

In [992]:
df

eid      name  gender department  age   salary  working_years birth_place
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
5  E016    Fundee  female    support   35  56600.0              3      Phuket
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [993]:
df.groupby("department")[['salary']].mean()

salary
department         
developer   52800.0
devops      67700.0
marketing   76550.0
support     49500.0

In [994]:
df.groupby("department").max()

eid      name gender  age   salary  working_years birth_place
department                                                                
developer   E013  Chantana   male   39  64200.0              4      Phuket
devops      E018     Harit   male   32  67700.0              5     Bangkok
marketing   E015   Ekkasit   male   39  80500.0              8  Suphanburi
support     E017   Gitiwit   male   35  56600.0              3  Suphanburi

In [995]:
df.groupby(["department","gender"])[['age', 'salary', 'working_years']].mean()

age   salary  working_years
department gender                              
developer  female  34.0  54850.0            3.5
           male    25.0  48700.0            2.0
devops     male    32.0  67700.0            5.0
marketing  female  39.0  72600.0            8.0
           male    37.0  80500.0            7.0
support    female  35.0  56600.0            3.0
           male    26.0  42400.0            2.0

In [996]:
df.groupby(["gender","department"])[['age', 'salary', 'working_years']].mean()

age   salary  working_years
gender department                              
female developer   34.0  54850.0            3.5
       marketing   39.0  72600.0            8.0
       support     35.0  56600.0            3.0
male   developer   25.0  48700.0            2.0
       devops      32.0  67700.0            5.0
       marketing   37.0  80500.0            7.0
       support     26.0  42400.0            2.0

In [997]:
df.groupby("department").min()

eid     name  gender  age   salary  working_years birth_place
department                                                                
developer   E011     Anda  female   25  45500.0              2     Bangkok
devops      E018    Harit    male   32  67700.0              5     Bangkok
marketing   E014  Donlaya  female   37  72600.0              7    Chonburi
support     E016   Fundee  female   26  42400.0              2      Phuket

In [998]:
df.groupby("department").count()

eid  name  gender  age  salary  working_years  birth_place
department                                                            
developer     3     3       3    3       3              3            3
devops        1     1       1    1       1              1            1
marketing     2     2       2    2       2              2            2
support       2     2       2    2       2              2            2

In [999]:
df.groupby("department")[['age', 'salary', 'working_years']].agg(["mean", "count"])

age         salary       working_years      
            mean count     mean count          mean count
department                                               
developer   31.0     3  52800.0     3           3.0     3
devops      32.0     1  67700.0     1           5.0     1
marketing   38.0     2  76550.0     2           7.5     2
support     30.5     2  49500.0     2           2.5     2

In [1000]:
df.groupby("department")["age"].agg(["mean", "count"])

mean  count
department             
developer   31.0      3
devops      32.0      1
marketing   38.0      2
support     30.5      2

In [1001]:
df.groupby("department")[["age"]].agg(["mean", "count"])

age      
            mean count
department            
developer   31.0     3
devops      32.0     1
marketing   38.0     2
support     30.5     2

In [1002]:
df.groupby("department").agg({"age":"min", "salary":"mean"})

age   salary
department              
developer    25  52800.0
devops       32  67700.0
marketing    37  76550.0
support      26  49500.0

In [1003]:
df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

age       salary
           min max     mean
department                 
developer   25  39  52800.0
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

**Quiz !!**

> จงจัดกลุ่มตาม birth_place โดยแสดงค่าเฉลี่ยของ age และ ค่าสูงสุด/ต่ำสุด ของ salary

In [1004]:
df.groupby("birth_place").agg({"age":"mean", "salary":["min", "max"]})

age   salary         
             mean      min      max
birth_place                        
Bangkok      35.5  64200.0  67700.0
Chonburi     34.0  45500.0  72600.0
Phuket       30.0  48700.0  56600.0
Suphanburi   31.5  42400.0  80500.0

## Grouping (2)

In [1005]:
df_group_obj = df.groupby("department")

In [1006]:
df_group_obj

In [1007]:
df_group_obj[['age', 'salary', 'working_years']].mean()

age   salary  working_years
department                              
developer   31.0  52800.0            3.0
devops      32.0  67700.0            5.0
marketing   38.0  76550.0            7.5
support     30.5  49500.0            2.5

In [1008]:
df_group_obj.max()

eid      name gender  age   salary  working_years birth_place
department                                                                
developer   E013  Chantana   male   39  64200.0              4      Phuket
devops      E018     Harit   male   32  67700.0              5     Bangkok
marketing   E015   Ekkasit   male   39  80500.0              8  Suphanburi
support     E017   Gitiwit   male   35  56600.0              3  Suphanburi

In [1009]:
dfg = df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

In [1010]:
dfg

age       salary
           min max     mean
department                 
developer   25  39  52800.0
devops      32  32  67700.0
marketing   37  39  76550.0
support     26  35  49500.0

In [1011]:
dfg.columns

MultiIndex([(   'age',  'min'),
            (   'age',  'max'),
            ('salary', 'mean')],
           )

In [1012]:
dfg[('age','min')]

department
developer    25
devops       32
marketing    37
support      26
Name: (age, min), dtype: int64

In [1013]:
dfg[[('age','min'),('salary','mean')]]

age   salary
           min     mean
department             
developer   25  52800.0
devops      32  67700.0
marketing   37  76550.0
support     26  49500.0

In [1014]:
dfg.columns

MultiIndex([(   'age',  'min'),
            (   'age',  'max'),
            ('salary', 'mean')],
           )

In [1015]:
["_".join(x) for x in dfg.columns]

['age_min', 'age_max', 'salary_mean']

In [1016]:
dfg.columns = ["_".join(x) for x in dfg.columns]

In [1017]:
dfg

age_min  age_max  salary_mean
department                               
developer        25       39      52800.0
devops           32       32      67700.0
marketing        37       39      76550.0
support          26       35      49500.0

In [1018]:
dfg[["age_min"]]

age_min
department         
developer        25
devops           32
marketing        37
support          26

In [1019]:
dfg.reset_index()

department  age_min  age_max  salary_mean
0  developer       25       39      52800.0
1     devops       32       32      67700.0
2  marketing       37       39      76550.0
3    support       26       35      49500.0

In [1020]:
dfg.reset_index(inplace=True)

In [1021]:
dfg

department  age_min  age_max  salary_mean
0  developer       25       39      52800.0
1     devops       32       32      67700.0
2  marketing       37       39      76550.0
3    support       26       35      49500.0

## Reload the Dataset

In [1022]:
df = pd.read_csv(CSV_PATH)

In [1023]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Iteration

In [1024]:
for index, row in df.iterrows():
  print(index)

0
1
2
3
4
5
6
7


In [1025]:
for index, row in df.iterrows():
  print(row["eid"], row["name"], row["salary"])

E011 Anda 64200.0
E012 Bordin 48700.0
E013 Chantana 45500.0
E014 Donlaya 72600.0
E015 Ekkasit 80500.0
E016 Fundee 56600.0
E017 Gitiwit 42400.0
E018 Harit 67700.0


In [1026]:
for index, row in df.iterrows():
  #row["shoud_pay_ot"] = "Something" << is not worked
  if row["salary"]>70000:
    df.loc[index,"should_pay_ot"] = "NO"
  elif row["salary"]>50000:
    df.loc[index,"should_pay_ot"] = "MAY BE"
  else:
    df.loc[index,"should_pay_ot"] = "YES"

In [1027]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

## Reload the Dataset

In [1028]:
df = pd.read_csv(CSV_PATH)

## Apply Function

In [1029]:
np.log10(1000)

np.float64(3.0)

In [1030]:
df["salary"]

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [1031]:
df["salary"].apply(np.log10)

0    4.807535
1    4.687529
2    4.658011
3    4.860937
4    4.905796
5    4.752816
6    4.627366
7    4.830589
Name: salary, dtype: float64

In [1032]:
df["salary"].apply(np.sqrt)

0    253.377189
1    220.680765
2    213.307290
3    269.443872
4    283.725219
5    237.907545
6    205.912603
7    260.192237
Name: salary, dtype: float64

In [1033]:
def times10(num):
  return num*10

In [1034]:
times10(5)

50

In [1035]:
df["age"]

0    39
1    25
2    29
3    39
4    37
5    35
6    26
7    32
Name: age, dtype: int64

In [1036]:
df["age"].apply(times10)

0    390
1    250
2    290
3    390
4    370
5    350
6    260
7    320
Name: age, dtype: int64

In [1037]:
df["age"].apply(lambda x: x*10)

0    390
1    250
2    290
3    390
4    370
5    350
6    260
7    320
Name: age, dtype: int64

In [1038]:
def consider_ot_payment(salary):
  result = ""
  if salary>70000:
    result = "NO"
  elif salary>50000:
    result = "MAY BE"
  else:
    result = "YES"

  return result

In [1039]:
consider_ot_payment(80000)

'NO'

In [1040]:
consider_ot_payment(60000)

'MAY BE'

In [1041]:
consider_ot_payment(30000)

'YES'

In [1042]:
df["salary"].apply(consider_ot_payment)

0    MAY BE
1       YES
2       YES
3        NO
4        NO
5    MAY BE
6       YES
7    MAY BE
Name: salary, dtype: object

In [1043]:
df["should_pay_ot"] = df["salary"].apply(consider_ot_payment)

In [1044]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

**Quiz !!**

> จงสร้างคอลัมน์ bonus โดยการคูณ salary กับ working_years ด้วย lambda function

In [1045]:
def bonus(row):
    return row["salary"] * row["working_years"]

df["bonus"] = df.apply(bonus, axis=1)
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot     bonus  
0        MAY BE  256800.0  
1           YES   97400.0  
2           YES  136500.0  
3            NO  580800.0  
4            NO  563500.0  
5        MAY BE  169800.0  
6           YES   84800.0  
7        MAY BE  338500.0

## Save into a CSV file

In [1046]:
df.to_csv("employee.csv")

In [1047]:
pd.read_csv("employee.csv")

Unnamed: 0   eid      name  gender department  age   salary  working_years  \
0           0  E011      Anda  female  developer   39  64200.0              4   
1           1  E012    Bordin    male  developer   25  48700.0              2   
2           2  E013  Chantana  female  developer   29  45500.0              3   
3           3  E014   Donlaya  female  marketing   39  72600.0              8   
4           4  E015   Ekkasit    male  marketing   37  80500.0              7   
5           5  E016    Fundee  female    support   35  56600.0              3   
6           6  E017   Gitiwit    male    support   26  42400.0              2   
7           7  E018     Harit    male     devops   32  67700.0              5   

  birth_place should_pay_ot     bonus  
0     Bangkok        MAY BE  256800.0  
1      Phuket           YES   97400.0  
2    Chonburi           YES  136500.0  
3    Chonburi            NO  580800.0  
4  Suphanburi            NO  563500.0  
5      Phuket        MAY BE  169800.0  
6  Suphanburi           YES   84800.0  
7     Bangkok        MAY BE  338500.0

In [1048]:
df.to_csv("employee1.csv", index=False)

In [1049]:
pd.read_csv("employee1.csv")

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot     bonus  
0        MAY BE  256800.0  
1           YES   97400.0  
2           YES  136500.0  
3            NO  580800.0  
4            NO  563500.0  
5        MAY BE  169800.0  
6           YES   84800.0  
7        MAY BE  338500.0



---
https://rathachai.creatier.pro/

## つづく